#!/bin/sh

case "$1" in
  start)
    echo "Starting the server"
    start-stop-daemon -S -n aesdsocket -- -d
    ;;
  stop)
    echo "Stopping the server"
    start-stop-daemon -K -n aesdsocket
    ;;
  *)
    echo "Usage: {start|stop}"
    exit 1
    ;;
esac

exit 0